#-------------------------------
# General Site Settings

title: Miles Cumiskey 
description: Multidisiplinary Designer and Developer
email: milescumiskey@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: 3D Models and Rigs, url: '#3D'}
- {name: Programming, url: '#code'}
- {name: Technical Writing, url: '#writing'}
- {name: Other Work, url: '#other'}
- {name: About, url: '#about'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'A portfolio website for Miles Cumiskey, technical 3D artist and programmer.'
  rel-author: 'https://github.com/mcumiskey'
  rel-publisher: 'https://github.com/mcumiskey'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **I am a technical artist and programmer, with a wide variety of skills that combine coding with creative work. I have experience in C++, C#, Java, HLSL, Unity, and Godot. I am also well-versed in 3D modeling, using Maya, Blender, Fusion360, and Solidworks for various projects. My focus is on UV mapping and retopology, but I am a jack of many trades, and am always learning more. Outside of tech, I am passionate about carpentry, education, and tabletop games.


#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/milesmeters'}
- {icon: 'instagram', link: 'https://www.instagram.com/miles.meters/'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UC3VCHLBmL6quSiSooXzsvTA'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/miles-cumiskey/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
